travis:
  secure:
    BINSTAR_TOKEN: NT6ULl7Gu/X1W6WGbW33oHPCGHPbh791Fe77dVyXz/fBrJuwZASYQnzNwUe9Lptxyr1yU7KS8Czi0GAu405clsPJ+1HdV6SzubXJI8LrJaPWh7hG5kEpG0r/b0DI0q7Rs4vKQXCwj9n/fUbcjygSGyifgnY448tC12ZR6XwCTg9koMdDFIYwwM1NqRlYq7SJ9F1mLaLb2kyvfgXc8QHmkT9HAv1veUJ2o3AwrpU4EOanX3Hqs7UkhAwlE6WKl1aci+6zgX/imhRUiMEzX6RlVJkkh+4asbZPAHMNZeMBlutjlIEgkJlmigbCilZxvGkBDcLMRaVdY3gSVvQyq2LwRfzW2cuQbh/xtZxt7bKUUpk4RdokwdDB2M9TUGxjihD3yAMlN5ii/ewlC3kvhFH18w0MX3z7ZWof7P3SdxR9N9IjD/OMHtoBPlUPIgUb8v3S8Fu8meRnnTeDfyQxRGCfSeMkVY9N4KJDijS4nAcJTSQJn/h7nJhMeMyzkgIM/LUAvSrX+D2js1pjrVjHMADBqIzFiUE+QjlZvMgWRF+TURgKdDwuOuqsl5J3QVVy38GYM3E1ayonUXMVsyiNQWSoCN8KgC7j2o7XROCAJzhy8lc3u8hVk2e23vtNLkRLqMmhgnw9/ObKHS85PO6pYrzjOsG3nXcRfyAvwoaoj6ZZDmI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
