travis:
  secure:
    BINSTAR_TOKEN: UGSDKm6GI1RIxM+a0JMQTi7Maj9TZW/X79oQI7HoZG00lIN8+RTT3X0FEmR8bdhqvNcgqkO3p0/XIkeK1c2yvVCjP6fRXAb2MavX82JbSK1W8FFdgDM1OpMuDGeKvs9U2F0et7mzJZeONWAcQMNsFfb1eJruHKQ/n7pS+AdgsdSN7P/6Jk32xzEExR54UuJJA6mVbwrdqd5nAYe/8bcK56nY4iBZf4BfkAotSOvQleW8B0Np4D0ttUYGTrHKknG34s8Go6itpOZ9DiNlcvL1/tyK5ukRU5LRo/rmpGgAmnC4j4oblw4HQaMkewudC/me9TJlf3J3/n4pSdSys/QijreyTKXhpZu25PVolp4IEluDWIiVHdFJLpbSKmx0QlIjII1p1fXhmIfIVq0jtvsIdQB6IuNIkD6vMbGBczNShgmssx13af1Qsl1flwTXK8Kq+IyNb6NJFn2qcd3y/pf52X94ZopHD8rkt81j6PxUIrhntIdrs/9HVrVRaIHcVYgmzSMSpt5IIaT7e9rz61mARS3yR8ppJXvGQJ8AGibMRkMyb0FkYyPSDs6Nig6m2YHdRNVQgzUa6XTwkAdIoB5Tm0P40D9p+u9Nv94usRoCXrChZ3YFV8s1iz20WOiKEZndtINabsfXfoEZ6HitOytw7lYGreXbIYiyDmlbvp0vvsA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
