travis:
  secure:
    BINSTAR_TOKEN: bzgT4EsGdIrc7FzlngvayJtKv9Vn3Sc3LpFlw/WF9wuiOW40+L18ibt9HAQ3NpqSRgXWKWhBEH2ysMbhjxQow9Qs8tKgT+c0BP67AWM5JKMOKSnDqMcNzozR2C9W3eC3flqpM29/K4L1NxYWYK3bejn9damV7AVm2gKJR669+1ho6O3gZ8bRLF5gUiPUcsjJwf5cyEPvR37X3PI2GUM8M/spQLuyKRWhomNz9NaUt33DpgLVnzl1hBH/SZdFsbEAcHng1Gw8qcUEVxCkxeBPvgEq+lZ9mgVX23j+KXlLJA1TIY+PKuFRS9xAOwPxVOvwtukERub1PsURQZ70WAMCzuKAEHG2cIM81MIHmqcKfp3HIn4db/vyaB4H+DUNs93cSvVYgjldTc3loxe8+a5g/T354v9CDeTHuaxqNXml/cPhX9B9zjP5iSpjLr8S8wtb+2TdmbygHntljt5LNWPV3eyjTUhKIy7kEz/IaPBoR4mUT30nU6nMK5f/1pg/psW1U5cKbj9UsfyYSCwa42VhUyaxOJiXjTsY80WQxFl3OzMgbk6j+v9VEuWv37vKQLFdLxmpP/e2QesAX9ON9NoKs8WEjrWA90pTK0K0VArLHoH4SgLl1wXxyhyp3vJeWIU+6Rz4BtWLYPyCzIIWe0ledx6RFFl96DoGwfCPOOkLSj0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
