travis:
  secure:
    BINSTAR_TOKEN: MlH21hd4xDcYFFWUB9HgbkZZYyyiiLY6qujPznDgySKc4RTXhkMo/b31kOGku2XE/W4GndnJylhO65SOx6nfz9naC32GmX2h4Swi3UmMsxPveq5sE398YAWijO5YcCzDPpqzblnGjs9BZCVzdxjdG31fejTVjFrOGsYxzD3XlC2WGH/Pww4R59OmI+shcydqVk7HQ8p1tMftqmXCYNZca8Rvqvvpz7595jgcLB/yMaKBu3zXq+NtKYkjRsDuD7Dc4KSoJFuvMpWa1Aj0eWcZonZz4HHLPB9pwJiAZ+HKRmcSkfGeIfGdSf7I2JgEj3CP3vF9ONzzRyjyied1VVbJg2GWTTC0HG/uJNjosLkvDp149eCVpJVOLolDoUDZrfc5QU8j0EWUxer+b1nQXb9bxHyKM2glm/b+lXYY83QLvdIXbQ7GV16FJfzPAKJ9qsHZdXuYAhhL6pK077fKvazF8IXEvfoBlYExF4jmEsbeexjE7tku9jCsbeYByyXUhGgJ0baUi00KTHJ8nXx9mMSduxKkHP7XNtVvrOj1jlleh6c6r+v+LbNP0xENUXOmI2M8N1QZu0qvi00HdbcYXDSolNG3Nr60goYIqo1UdpDGdAolxbqL0azV7hbIVbydVMmGb6Lz7P0S6xjkRMVmpOW0tfM3G4XQjjJE502aUEf/GYE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
