travis:
  secure:
    BINSTAR_TOKEN: WJcj465sSuu5uRbWJI0njLwVUMvMl5rCf7+6bBpxn0d8AHfTMcI25Ztnehh96so4SXp7IKQG1oLKh/Mzs6nvrJJJrLNSuNWBDCqQvYnbx+WCeBa1rAF4kedNwgW4yoiGyNICE8oPMdW+pSvYSIVOELqM4Rqp0pO1doEJoqusgwLMy2+ZH6xVDUv7UnusAxZTtNXZXE2oT2NtELldX2+IYh4m9dj5Lb40B0RRpBMdKmuhlwFWFYFqECj1lb/EeZwKLq37KuE1dv89M83AF6yHPYo43a7AcmvgE4zGf6MRaAxKDP2QdsdrfNTrHqqR1aiAOrl/w1DLpw5hBxE25JQULF+xOL3gGdtBrDYyXmBlq/mVztJUAjXUikZZth6zvWEDIvwv3PMXZJ7SqTFtt9pi1s40XPiflRY6DTJXFOgTsRbTzun9otA+AN2BL2NiB898o2GiyY4Dt6pYJWiqo4QshPftBY+5Di4zZue0w6PBDeDDcBIzyvUGOWGYlVTs8XJ2Gghjzbx5O815N7l4a7m9ZYumYOFkoUPkVFdg9JavG28AYq1Wk7uGYTp7WVfMxsZti63m20peXeXaX6xtOwz+VFMgqjtiZeCnRdVGhtT9IxgrvqTOPT2QVR2Gg4mKr3mzXjLMyOpE8GvPjVLC1gy/DbMXYykQB5x7gSjpumrejHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
